### ISSUE TITLE
Recording time left incorrect

### ISSUE THREAD

**Issue by jalmarverbraak** [bitfocus/companion-module-bmd-hyperdeck#106]
We have noticed that the variable recording time does not display the correct time that is left to record on the disk. The minutes and seconds seem to be correct but the hours are not correct. on the hyperdeck it shows we have 52:45:21 left to record but on the streamdeck it says only 04:45:21. Another hyperdeck has 72:43:07 but on the streamdeck it shows we have 00:43:07. 
Would love to hear if there is a solution for this.

**Comment by sphlabs** [comment]
The code converting seconds to readable time didn't allow for there being over 24 hours available.

This is fixed now.

**Comment by mattescouade** [comment]
I am still having issues with this on Companion 3.2.2. Am I missing something?

**Comment by sphlabs** [comment]
The fix is not in 3.2.2. Try the 3.3.0 beta and that should fix the problem (a 3.3.0 stable release is not far off).
